--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IcyEndymion004/Minecraft-Sex-Plugin-Pocketmine
build-by-default: true
branches:
- main
projects:
  Minecraft-Sex-Plugin-Pocketmine:
    path: ""
...
